# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'BasicApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicApp
  pod 'Clix', :path => '../..'

end

target 'ClixNotificationExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClixNotificationExtension
  pod 'Clix', :path => '../..'

end
