name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "Samples/**"
      - "README.md"

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache Derived Data
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: derived-data-${{ runner.os }}-${{ hashFiles('**/*.xcodeproj/**', '**/*.xcworkspace/**') }}

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run Lint
        run: make lint

      - name: Run Build
        run: make build
